// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentInfoSystem.Data;

#nullable disable

namespace StudentInfoSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentInfoSystem.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Code = "BSCS",
                            DepartmentId = 1,
                            Name = "Bachelor of Science in Computer Science",
                            Units = 4
                        },
                        new
                        {
                            CourseId = 2,
                            Code = "BSIT",
                            DepartmentId = 2,
                            Name = "Bachelor of Science in Information Technology",
                            Units = 4
                        },
                        new
                        {
                            CourseId = 3,
                            Code = "BSCpE",
                            DepartmentId = 3,
                            Name = "Bachelor of Science in Computer Engineering",
                            Units = 4
                        });
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Code = "CS",
                            Description = "Department of Computer Science and Technology",
                            Name = "Computer Science"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Code = "IT",
                            Description = "Department of Information Technology",
                            Name = "Information Technology"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Code = "ENG",
                            Description = "Department of Engineering",
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            EnrollmentDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Enrolled",
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            EnrollmentDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Enrolled",
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            EnrollmentId = 3,
                            EnrollmentDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Enrolled",
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            EnrollmentId = 4,
                            EnrollmentDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Enrolled",
                            StudentId = 3,
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstructorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            DepartmentId = 1,
                            Email = "m.santos@school.edu",
                            EmployeeId = "EMP001",
                            FirstName = "Maria",
                            HireDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Santos",
                            Specialization = "Software Engineering"
                        },
                        new
                        {
                            InstructorId = 2,
                            DepartmentId = 2,
                            Email = "j.reyes@school.edu",
                            EmployeeId = "EMP002",
                            FirstName = "Jose",
                            HireDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reyes",
                            Specialization = "Database Systems"
                        },
                        new
                        {
                            InstructorId = 3,
                            DepartmentId = 1,
                            Email = "a.cruz@school.edu",
                            EmployeeId = "EMP003",
                            FirstName = "Ana",
                            HireDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cruz",
                            Specialization = "Web Development"
                        });
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentId");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            Email = "juan@student.edu",
                            EnrollmentDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Juan",
                            Gender = "Male",
                            LastName = "Dela Cruz",
                            StudentNumber = "2024-00001"
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2,
                            Email = "maria@student.edu",
                            EnrollmentDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maria",
                            Gender = "Female",
                            LastName = "Reyes",
                            StudentNumber = "2024-00002"
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 1,
                            Email = "pedro@student.edu",
                            EnrollmentDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pedro",
                            Gender = "Male",
                            LastName = "Garcia",
                            StudentNumber = "2024-00003"
                        });
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Schedule")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Code = "CS101",
                            InstructorId = 1,
                            Name = "Data Structures and Algorithms",
                            Room = "Room 201",
                            Schedule = "MWF 8:00-9:00",
                            Units = 3
                        },
                        new
                        {
                            SubjectId = 2,
                            Code = "IT201",
                            InstructorId = 2,
                            Name = "Database Management Systems",
                            Room = "Room 302",
                            Schedule = "TTH 9:00-10:30",
                            Units = 3
                        },
                        new
                        {
                            SubjectId = 3,
                            Code = "CS301",
                            InstructorId = 3,
                            Name = "Web Development",
                            Room = "Lab 1",
                            Schedule = "MWF 10:00-11:00",
                            Units = 3
                        });
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Course", b =>
                {
                    b.HasOne("StudentInfoSystem.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Enrollment", b =>
                {
                    b.HasOne("StudentInfoSystem.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentInfoSystem.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Instructor", b =>
                {
                    b.HasOne("StudentInfoSystem.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Student", b =>
                {
                    b.HasOne("StudentInfoSystem.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Subject", b =>
                {
                    b.HasOne("StudentInfoSystem.Models.Instructor", "Instructor")
                        .WithMany("Subjects")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Course", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Instructor", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentInfoSystem.Models.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
